#!/usr/bin/env ruby

require 'rubygems'

lib_dir = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift lib_dir
Dir["#{lib_dir}/**/*.rb"].each { |file| require File.basename(file) }

App.new.cycletime
