#!/usr/bin/env ruby

require 'rubygems'

lib_dir = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift lib_dir
Dir["#{lib_dir}/**/*.rb"].each { |file| require File.basename(file) }

issue_details = IssueLoader.load_issues
project_metrics = ProjectMetrics.new(issue_details)
project_metrics.cycletime
project_metrics.kickbacks
